# Project Identity
spring.application.name=CAAS_Platform

# Database Configuration
# These variables match the ones defined in docker-compose.yml
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/caasdb?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:w|[]W6R|fRm?j2HyQ_NeUguJ*q-(}

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Security Placeholder (For Sondous)
# This will be used for JWT signing
jwt.secret=${JWT_SECRET:temporary_local_secret_key}