# Project Identity
spring.application.name=CAAS_Platform

# Database Configuration
# These variables match the ones defined in docker-compose.yml
spring.datasource.url=jdbc:mysql://caas-db.cvc80k8c28ms.eu-north-1.rds.amazonaws.com:3306/caasdb?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=w|[]W6R|fRm?j2HyQ_NeUguJ*q-(

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Security Placeholder (For Sondous)
# This will be used for JWT signing
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
